name: chatgpt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  dio: ^4.0.4
  google_fonts: ^3.0.1
  flutter_launcher_icons: ^0.9.2



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  image_path: "images/gpt.png"
  android: true
  ios: true
  remove_alpha_ios: true
